#@server= https://infantejonathan-upgraded-space-engine-9pwgrwpv9gwfpw46-8080.preview.app.github.dev/

@server = https://evc03.onrender.com
###

@apiserver = {{server}}/api/curso

###
GET {{server}}/
###
GET {{server}}/codigo
###
GET {{server}}/nombre-completo
###
GET {{apiserver}}/listar
###
POST {{apiserver}}/nuevo
Content-Type: application/x-www-form-urlencoded

nombre=Machine Learning&creditos=4
###
DELETE {{apiserver}}/eliminar
Content-Type: application/x-www-form-urlencoded

id=1